### PR TITLE
August update - imagemagick version update

### PR DESCRIPTION
**Pull request by g7morris**

### CODE REVIEW

**Comment by g7morris** [comment]
Followed the steps for the local isle-builder (which works great) 

When I go to run: `docker buildx build --push --platform linux/arm64,linux/amd64 --tag islandora.io/isle-imagemagick:august-2024-update .` in the `isle-imagemagick/imagemagick` directory.

I get the following failure on Linux (Fedora Workstation 40) running Docker engine `27.1.1` and Compose `2.29.1`

```bash
sudo apk add "${PACKAGES[@]}":
0.258 sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
------
Dockerfile:25
```

Am now testing on MacOS instead.

**Comment by g7morris** [comment]
Not getting far on a `MacOS Sonoma 14.5 (23F79)` running an `Apple M1 Silicon` chip and `Docker Desktop Version 4.33.0 (160616)` with `Engine: 27.1.1` and `Compose: v2.29.1-desktop.1`

Not sure what I'm missing here? This is all out of the box and as directed. 🤷 

1. isle-builder 

* `make port`

```bash
Makefile:91: target `/Users/gavin/Library/Application' given more than once in the same rule.
Makefile:104: warning: overriding commands for target `&'
Makefile:93: warning: ignoring old commands for target `&'
  Registry                       https://islandora.io:62101
  UI                             http://islandora.io:55001
```

* `make use`

```bash
[+] Running 2/2
 ✔ Container isle-builder-registry     Started                                                                                               0.5s 
 ✔ Container isle-builder-registry-ui  Started                                                                                               0.4s 
ERROR: failed to find instance "isle-builder" for append
make: *** [start] Error 1
```

2. `cd isle-imagemagick/imagemagick`

3. `docker buildx build --push --platform linux/arm64,linux/amd64 --tag islandora.io/isle-imagemagick:latest .`

```bash
 => CACHED [linux/amd64 stage-0 1/4] FROM docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5   0.0s
 => => resolve docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5                              0.0s
 => [internal] load build context                                                                                                            0.0s
 => => transferring context: 111B                                                                                                            0.0s
 => CACHED [linux/arm64 stage-0 1/4] FROM docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5   0.0s
 => => resolve docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5                              0.0s
 => ERROR [linux/amd64 stage-0 2/4] RUN --mount=type=cache,id=abuild-apk-amd64,sharing=locked,target=/var/cache/apk     apk add         al  10.2s
 => ERROR [linux/arm64 stage-0 2/4] RUN --mount=type=cache,id=abuild-apk-arm64,sharing=locked,target=/var/cache/apk     apk add         al  10.2s
------                                                                                                                                            
 > [linux/amd64 stage-0 2/4] RUN --mount=type=cache,id=abuild-apk-amd64,sharing=locked,target=/var/cache/apk     apk add         alpine-sdk         bash         sudo     &&     adduser -G abuild -g "Alpine Package Builder" -s /bin/ash -D builder &&     echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers:
0.161 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
5.175 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)
5.176 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
10.19 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)
10.19 ERROR: unable to select packages:
10.19   alpine-sdk (no such package):
10.19     required by: world[alpine-sdk]
10.19   bash (no such package):
10.19     required by: world[bash]
10.19   sudo (no such package):
10.19     required by: world[sudo]
------
------
 > [linux/arm64 stage-0 2/4] RUN --mount=type=cache,id=abuild-apk-arm64,sharing=locked,target=/var/cache/apk     apk add         alpine-sdk         bash         sudo     &&     adduser -G abuild -g "Alpine Package Builder" -s /bin/ash -D builder &&     echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers:
0.143 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz
5.157 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)
5.157 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz
10.17 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)
10.17 ERROR: unable to select packages:
10.17   alpine-sdk (no such package):
10.17     required by: world[alpine-sdk]
10.17   bash (no such package):
10.17     required by: world[bash]
10.17   sudo (no such package):
10.17     required by: world[sudo]
------
Dockerfile:6
--------------------
   5 |     
   6 | >>> RUN --mount=type=cache,id=abuild-apk-${TARGETARCH},sharing=locked,target=/var/cache/apk \
   7 | >>>     apk add \
   8 | >>>         alpine-sdk \
   9 | >>>         bash \
  10 | >>>         sudo \
  11 | >>>     && \
  12 | >>>     adduser -G abuild -g "Alpine Package Builder" -s /bin/ash -D builder && \
  13 | >>>     echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  14 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add         alpine-sdk         bash         sudo     &&     adduser -G abuild -g \"Alpine Package Builder\" -s /bin/ash -D builder &&     echo \"builder ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers" did not complete successfully: exit code: 3

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/la4deibbfpmdvyg3v8cauytik
```

That's odd the "temporary error" - bad network timing? 

I guess I'm not supposed to attempt to update this then. Sorry @nigelgbanks everytime I try to help here, I just step on land mines.

**Comment by nigelgbanks** [comment]
I added a fix to the builder repository: https://github.com/Islandora-Devops/isle-builder/commit/bbf6c22d1d0d510f923fd4aa89eb0cccd61c0e06. The behaviour of a command changed. I'm not sure about the rest of your issues. I was able to build locally using just docker and with the `isle-builder` to do a multiplatform build.

**Comment by nigelgbanks** [comment]
On Fedora 

> sudo apk add "${PACKAGES[@]}":
0.258 sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

Might relate to SELinux? There is always problems with Docker and SELinux.

> Makefile:91: target `/Users/gavin/Library/Application' given more than once in the same rule.
Makefile:104: warning: overriding commands for target `&'
Makefile:93: warning: ignoring old commands for target `&'
  Registry                       https://islandora.io:62101
  UI                             http://islandora.io:55001
  
  My guess is that it's using the Make bundled with OSX rather than GNU Make?
  
  > [+] Running 2/2
 ✔ Container isle-builder-registry     Started                                                                                               0.5s 
 ✔ Container isle-builder-registry-ui  Started                                                                                               0.4s 
ERROR: failed to find instance "isle-builder" for append
make: *** [start] Error 1
 
I added a fix to the builder repository: https://github.com/Islandora-Devops/isle-builder/commit/bbf6c22d1d0d510f923fd4aa89eb0cccd61c0e06.

> That's odd the "temporary error" - bad network timing?

Seems so, maybe the alpine repository was not reachable at that time you ran the command?

**Comment by g7morris** [comment]
Thanks @nigelgbanks I'll look into tuning this all for a next time in September ish. Hope your summer is going well. Cheers.

**Pull request merged**
